title: "Larry C"
logo: "/images/Larry_photo.jpg?raw=true"
description: >
  I am Larry C and I am a Reman Lover. 
  <br><br>
  I'm passionate about data, strategy, and innovation.
  <br><br>
  <a href="https://www.linkedin.com/in/larrychencpa/" target="_blank">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal

show_downloads: false
google_analytics: ""  # Add your GA tracking ID if needed, e.g., "UA-XXXXXXXXX-X"
author:
  name: "Larry C"
  email: "larrychenpro@gmail.com"

# Build settings
markdown: kramdown
